#ifndef RF_H9_CHOOSE_INCLUDE_H
#define RF_H9_CHOOSE_INCLUDE_H
#include "common.h"

/*BOUNDARY:H9:IF-GROUP:BEGIN*/
#if RF_PICK_H1
  /*BOUNDARY:H9:IF-ARM:INCLUDE-H1:BEGIN*/
  #include "h1.h"
  /*BOUNDARY:H9:IF-ARM:INCLUDE-H1:END*/
#else
  /*BOUNDARY:H9:ELSE-ARM:INCLUDE-H2A:BEGIN*/
  #include "h2a.h"
  /*BOUNDARY:H9:ELSE-ARM:INCLUDE-H2A:END*/
#endif
/*BOUNDARY:H9:IF-GROUP:END*/

#endif
