//===--- RefoldSourceGraphProof.cpp -----------------------------*- C++ -*-===//
//
// Source-graph preservation proof helpers for clang-refold.
//
//===----------------------------------------------------------------------===//

#include "include/RefoldSourceGraphProof.h"

#include "include/IncludeSpellingHelpers.h"
#include "core/RefoldLangOptions.h"
#include "source/RefoldPreprocessingDirectiveScanner.h"

namespace clang {
namespace refold {
namespace source_graph {

std::optional<std::string>
safeSourceGraphRelativeIncludePath(const RefoldModel::IncludeItem &include) {
  if (include.angled)
    return std::nullopt;

  llvm::StringRef target = include.target;
  if (target.size() < 2 || target.front() != '"' || target.back() != '"')
    return std::nullopt;

  llvm::StringRef path = target.drop_front().drop_back();
  if (!safeSynthesizedRelativeIncludeOperandPath(path))
    return std::nullopt;

  return path.str();
}

bool lineHasPreprocessingDirectiveIntroducer(
    llvm::StringRef text, const clang::LangOptions &lexLang) {
  PreprocessingDirectiveScanResult scan =
      scanPreprocessingDirectives(text, lexLang);

  // Scanner inconsistency is itself unsafe for callers that use this predicate
  // as a macro-state neutrality proof.  Returning true preserves the previous
  // fail-closed contract even when no exact directive interval was recovered.
  return !scan.directives.empty() || !scan.diagnostics.empty();
}

MaterializedIncludeReplayAlias classifyMaterializedIncludeReplayAlias(
    llvm::StringRef materializedText, llvm::StringRef sourceGraphPath,
    const clang::LangOptions &lexLang) {
  PreprocessingDirectiveScanResult scan =
      scanPreprocessingDirectives(materializedText, lexLang);
  if (!scan.IsComplete())
    return MaterializedIncludeReplayAlias::UnprovenInclude;

  for (const PreprocessingDirectiveLine &directive : scan.directives) {
    if (directive.headKind != PreprocessingDirectiveHeadKind::Identifier ||
        directive.keyword != "include")
      continue;

    // A macro-derived, angled, malformed, or otherwise non-simple operand can
    // name the generated sidecar after preprocessing.  Without evaluating that
    // directive in its original state, alias safety must reject it.
    if (directive.includeOperandKind !=
            PreprocessingIncludeOperandKind::SimpleQuotedHeader ||
        !directive.simpleQuotedIncludePath) {
      return MaterializedIncludeReplayAlias::UnprovenInclude;
    }

    if (llvm::StringRef(*directive.simpleQuotedIncludePath) == sourceGraphPath)
      return MaterializedIncludeReplayAlias::SamePath;
  }

  return MaterializedIncludeReplayAlias::None;
}

bool sourceGraphIncludePathIsUnaliasedOrCoherent(
    const SourceGraphProofInputs &inputs,
    const RefoldModel::IncludeItem &include, llvm::StringRef sourceGraphPath,
    llvm::StringRef candidateBytes, const SourceGraphProofServices &services) {
  // Materialized include bytes must be scanned under the producer language
  // mode.  Construct the mode once for this complete alias proof so digraph,
  // trigraph, comment, and literal recognition agrees with the main refold run
  // without adding another scheduler dependency.
  const clang::LangOptions lexLang =
      makeRefoldLexLangOptions(inputs.model.GetPPLang());

  // A source-graph output written under an original quoted include path is a
  // path-level edit, not an include-site-local edit: every surviving
  // `#include "that/path.h"` in the emitted TU will read the generated bytes.
  // Therefore preserving one include edge is admissible only when all same-path
  // top-level include sites are either materialized away, or are themselves
  // source-graph-preserved with exactly the same owner bytes.  Otherwise the
  // sidecar would either change an untouched alias or create conflicting bytes
  // for the same generated file.
  for (const RefoldModel::IncludeItem &other : inputs.model.GetIncludes()) {
    if (other.id == include.id)
      continue;
    if (other.parent ||
        !services.paths.PathsEqual(other.sitePath, inputs.tuPath))
      continue;

    std::optional<std::string> otherPath =
        safeSourceGraphRelativeIncludePath(other);
    if (!otherPath || llvm::StringRef(*otherPath) != sourceGraphPath)
      continue;

    auto otherExpansionIt = inputs.includeExpansion.find(other.id);
    if (otherExpansionIt == inputs.includeExpansion.end())
      return false;

    if (!services.includeHasIncluderSuppliedLineControlMacroState(other)) {
      // The alias is dirty but does not satisfy the source-graph proof, so the
      // normal single-output path will materialize it into the TU.  It will not
      // survive as a same-path include edge.
      continue;
    }

    if (llvm::StringRef(otherExpansionIt->second) != candidateBytes)
      return false;
  }

  for (const RefoldModel::IncludeItem &other : inputs.model.GetIncludes()) {
    if (other.id == include.id)
      continue;
    if (other.parent ||
        !services.paths.PathsEqual(other.sitePath, inputs.tuPath))
      continue;

    auto otherExpansionIt = inputs.includeExpansion.find(other.id);
    if (otherExpansionIt == inputs.includeExpansion.end())
      continue;

    const MaterializedIncludeReplayAlias replayAlias =
        classifyMaterializedIncludeReplayAlias(
            otherExpansionIt->second, sourceGraphPath, lexLang);
    if (replayAlias == MaterializedIncludeReplayAlias::SamePath)
      return false;
    if (replayAlias == MaterializedIncludeReplayAlias::UnprovenInclude)
      return false;
  }

  const MaterializedIncludeReplayAlias candidateReplayAlias =
      classifyMaterializedIncludeReplayAlias(candidateBytes, sourceGraphPath,
                                               lexLang);
  if (candidateReplayAlias == MaterializedIncludeReplayAlias::SamePath)
    return false;
  if (candidateReplayAlias == MaterializedIncludeReplayAlias::UnprovenInclude)
    return false;

  return true;
}

SourceGraphOutput makeSourceGraphOutput(const RefoldModel::IncludeItem &include,
                                        llvm::StringRef relativePath,
                                        llvm::StringRef bytes,
                                        bool cleanupOnly) {
  SourceGraphOutput output;
  output.includeId = include.id;
  output.relativePath = relativePath.str();
  output.originalTarget = include.target.str();
  if (include.resolvedPath)
    output.resolvedPath = include.resolvedPath->str();
  output.bytes = bytes.str();
  output.cleanupOnly = cleanupOnly;
  return output;
}

SourceGraphOwnerPreservationPlan
planSourceGraphOwnerPreservation(const SourceGraphProofInputs &inputs,
                                 const RefoldModel::IncludeItem &include,
                                 llvm::StringRef candidateBytes,
                                 const SourceGraphProofServices &services) {
  SourceGraphOwnerPreservationPlan plan;

  // This is intentionally narrower than "dirty header".  Most header edits in
  // the existing single-output backend are supposed to materialize into the TU.
  // The source-graph path is selected only when the modified header contains
  // producer-proven source line-control state whose operands depend on macro
  // definitions supplied by the immediate includer.  Materializing that owner
  // into the TU is token-sound, but it is no longer the most precise
  // source-graph refolding because the header remains the owner of the repaired
  // source line-control directive.
  if (!services.includeHasIncluderSuppliedLineControlMacroState(include))
    return plan;

  std::optional<std::string> sourceGraphPath =
      safeSourceGraphRelativeIncludePath(include);
  if (!sourceGraphPath)
    return plan;

  if (services.includeSubtreeHasLayoutOnlyMaterializationSeed(include.id)) {
    // Source-graph sidecars are path-level artifacts.  They can replace the
    // bytes read from a header path, but they cannot realize an edit to the
    // caller's PP layout at this particular include edge.  A byte-only raw
    // layout hunk seeded from an include boundary is therefore an
    // include-site-local obligation and must be emitted by replacing the
    // include directive in the owner surface, not by writing a sidecar that
    // every surviving same-path include would observe.
    plan.rejectedCleanupRelativePath = *sourceGraphPath;
    return plan;
  }

  if (!sourceGraphIncludePathIsUnaliasedOrCoherent(
          inputs, include, *sourceGraphPath, candidateBytes, services)) {
    plan.rejectedCleanupRelativePath = *sourceGraphPath;
    return plan;
  }

  plan.preservedRelativePath = *sourceGraphPath;
  return plan;
}

SourceGraphOwnerPreservationOutputPlan planSourceGraphOwnerPreservationOutput(
    const SourceGraphProofInputs &inputs,
    const RefoldModel::IncludeItem &include, llvm::StringRef candidateBytes,
    const SourceGraphProofServices &services) {
  SourceGraphOwnerPreservationOutputPlan outputPlan;
  SourceGraphOwnerPreservationPlan plan = planSourceGraphOwnerPreservation(
      inputs, include, candidateBytes, services);

  if (plan.rejectedCleanupRelativePath) {
    // Source-graph sidecars are path-level artifacts beside the emitted TU.  A
    // previous run may have written a sidecar for a path that this run no
    // longer proves admissible, for example after a same-spelling include
    // becomes a surviving alias.  The driver may remove the stale file only if
    // its bytes still exactly match this rejected generated body and the file
    // is not the producer-resolved input header.
    outputPlan.rejectedCleanupOutput = makeSourceGraphOutput(
        include, *plan.rejectedCleanupRelativePath, candidateBytes,
        /*CleanupOnly=*/true);
  }

  if (plan.preservedRelativePath) {
    outputPlan.preservedOutput = makeSourceGraphOutput(
        include, *plan.preservedRelativePath, candidateBytes,
        /*CleanupOnly=*/false);
  }

  return outputPlan;
}

} // namespace source_graph
} // namespace refold
} // namespace clang
